package com.bonusflowpj.domain;

public enum AuditAction {
    CHANGE_USER_EMAIL,
    USER_CREATED,
    USER_PROFESSIONAL_LINKED,
    USER_PROFESSIONAL_UNLINKED,
    USER_LOGIN_WITHOUT_PROFESSIONAL_BLOCKED,
    USER_ROLE_GRANT_BLOCKED,
    USER_EMAIL_CHANGED,
    USER_ROLE_CHANGED,
    USER_DEACTIVATED,
    USER_REACTIVATED,
    SUPER_ADMIN_DEACTIVATION_BLOCKED,
    PROFESSIONAL_DOCUMENT_CHANGED,
    PROFESSIONAL_DEACTIVATED,
    PROFESSIONAL_REACTIVATED,
    INSTITUTION_DEACTIVATED,
    INSTITUTION_REACTIVATED,
    ORGANIZATION_UNIT_MOVED
}
